GET http://localhost:3000/users
###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Vladimir7",
  "about": "Student7",
  "avatar" : "https://kartinkin.net/uploads/posts/2022-02/1644872596_8-kartinkin-net-p-kotiki-kartinki-8.jpg"
}
###
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Vlad",
  "about": "Stud"
}
###
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar" : "https://kartinkin.net/uploads/posts/2022-02/1644872596_8-kartinkin-net-p-kotiki-kartinki-0.jpg"
}
###
GET  http://localhost:3000/cards
###
POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "Cat0",
  "link" : "https://kartinkin.net/uploads/posts/2022-02/1644872596_8-kartinkin-net-p-kotiki-kartinki-0.jpg"
}
###

DELETE http://localhost:3000/cards/62f25b2d73f859575a910ece

###
PUT http://localhost:3000/cards/62f0653023bab40a6ce17221/likes
###
DELETE http://localhost:3000/cards/62f0653023bab40a6ce17221/likes
###